ボタン内矢印をSVGで作成
q-abe/techlab-clone pull request #12
Opened 2024-02-02 06:32 UTC by q-abe

2024-02-02 06:44 UTC, q-abe commented on src/components/atoms/Button.tsx
> +        transform: translate(14px, -16px);
ここに`rotate();`追加で回転させれば向き違いが必要ないと思い右しか作成しておりません。

2024-02-02 12:43 UTC, q-abe commented on src/components/atoms/Button.tsx
> +        transform: translate(14px, -16px);
解消。[91be781](https://github.com/q-abe/techlab-clone/pull/12/commits/91be7811c78e0f0fb1c72d98e1bd1a72930d409c)

2024-02-05 01:31 UTC, q-nishimura requested changes

2024-02-05 01:31 UTC, q-nishimura commented on src/components/atoms/Button.stories.tsx
> +        onClick: () => {
ここって自動整形でこうなりますか？
() => {} がよく見る形なんですが、自動整形でこうなるならこのままで問題無いです

2024-02-05 01:31 UTC, q-nishimura commented on src/components/atoms/Button.tsx
> +                <ArrowIcon css={arrowStyle} direction={"right"} rotateNum={0}/>
right(等、定義済みの４つ)の場合はrotateNum無しで渡すようにしたいです。

2024-02-05 01:31 UTC, q-nishimura commented on src/components/atoms/symbols/ArrowIcon.stories.tsx
> +};
customのStoryを作ってください

2024-02-05 01:34 UTC, q-abe commented on src/components/atoms/Button.stories.tsx
> +        onClick: () => {
どうやら自動整形のようです😅

2024-02-05 02:01 UTC, q-nishimura commented on src/components/atoms/Button.stories.tsx
> +        onClick: () => {
🆗

2024-02-05 02:39 UTC, q-abe commented on src/components/atoms/Button.tsx
> +                <ArrowIcon css={arrowStyle} direction={"right"} rotateNum={0}/>
rotateNumを無しで渡すことも許容いたしました。
[4fb527c](https://github.com/q-abe/techlab-clone/pull/12/commits/4fb527c749f69d393f1550bbf6e920ec4fead52b)

2024-02-05 02:39 UTC, q-abe commented on src/components/atoms/symbols/ArrowIcon.stories.tsx
> +};
custom以外にも上下左右を作成いたしました！
[60d890e](https://github.com/q-abe/techlab-clone/pull/12/commits/60d890e1e4f6db8132f6b27253df4d3d95e8d507)

2024-02-05 02:42 UTC, q-abe commented on src/components/atoms/symbols/ArrowIcon.tsx
> +    rotateNum?: number | 0;
numberの値を範囲指定しようと思いましたが、
どんな値でも問題なかったので特に指定していません。

2024-02-05 02:48 UTC, q-nishimura requested changes

2024-02-05 02:48 UTC, q-nishimura commented on src/components/atoms/symbols/ArrowIcon.stories.tsx
> +export const cystomArrow: Story = {
@q-abe 
cystomに打ち間違えてます
あと、せっかくなので変な角度を見せておきたいです

2024-02-05 02:58 UTC, q-abe commented on src/components/atoms/symbols/ArrowIcon.stories.tsx
> +export const cystomArrow: Story = {
typo失礼いたしました💦

角度も斜めに修正いたしました！

[2b934b3](https://github.com/q-abe/techlab-clone/pull/12/commits/2b934b3e704fbae40dd4ab48dec85c0926accd53)

2024-02-05 03:01 UTC, q-nishimura commented on src/components/atoms/symbols/ArrowIcon.stories.tsx
> +export const cystomArrow: Story = {
🆗

2024-02-05 03:02 UTC, q-nishimura approved these changes

2024-02-05 03:09 UTC, merged