Accordionの作成
q-abe/techlab-clone pull request #16
Opened 2024-02-07 04:21 UTC by q-abe

#まずはJSONデータの追加確認依頼。

2024-02-07 04:42 UTC, q-nishimura commented on src/api/ArticleTypes.ts
> +export type ArticleTypes = {
Typeの定義というのはデータの実体とはまた違うので、フォルダを分けた方がいいです

2024-02-07 05:28 UTC, q-abe commented on src/api/ArticleTypes.ts
> +export type ArticleTypes = {
apiではなくentityフォルダへ移動しました。
[92a3218](https://github.com/q-abe/techlab-clone/pull/16/commits/92a32189ff2ef93ca6c2b02754a6f29a70c048fd)

2024-02-08 04:37 UTC, q-nishimura requested changes

2024-02-08 04:37 UTC, q-nishimura commented on src/components/molecules/Accordion.tsx
> +            <dd css={isOpen ? contentOpen : content}>
css= の中なので自明ではあるんですが、他の数値などの変数と少し紛らわしいので、~~Styleと付けてください
（一般的にこれが絶対というわけではないですが、今回は）

2024-02-08 04:37 UTC, q-nishimura commented on src/entity/TagTypes.ts
> +export type AuthorTypes = {
変え忘れてます

2024-02-08 04:37 UTC, q-nishimura commented on src/api/ArticlesCountMockDate.json
> +[
MockDat'e' になってます

2024-02-08 04:37 UTC, q-nishimura commented on src/components/molecules/Accordion.tsx
> +    year: string;
ArticlesCountOfYearにyearが入ってるのでこのyearは要らないように思います

2024-02-08 05:55 UTC, q-abe commented on src/components/molecules/Accordion.tsx
> +    year: string;
ArticlesCountOfYearの中から取得する様にしてpropsを削除いたしました。
[d90a2fa](https://github.com/q-abe/techlab-clone/pull/16/commits/d90a2fae3b5e2f6301ce7cf1b3ae9991d2769dfb)

2024-02-08 05:55 UTC, q-abe commented on src/api/ArticlesCountMockDate.json
> +[
タイポ失礼しました。修正してます。
[4783c93](https://github.com/q-abe/techlab-clone/pull/16/commits/4783c9319c35df91c45b10955c6ddd55e2c5af89)

2024-02-08 05:55 UTC, q-abe commented on src/entity/TagTypes.ts
> +export type AuthorTypes = {
変更漏れ失礼いたしました。変更しました。
[4783c93](https://github.com/q-abe/techlab-clone/pull/16/commits/4783c9319c35df91c45b10955c6ddd55e2c5af89)

2024-02-08 05:56 UTC, q-abe commented on src/components/molecules/Accordion.tsx
> +            <dd css={isOpen ? contentOpen : content}>
他のcssの名前にはつけているので統一したほうがいいですね。
変更しております！
[4783c93](https://github.com/q-abe/techlab-clone/pull/16/commits/4783c9319c35df91c45b10955c6ddd55e2c5af89)

2024-02-08 06:00 UTC, q-nishimura approved these changes

2024-02-08 06:30 UTC, merged