Featureの作成
q-abe/techlab-clone pull request #23
Opened 2024-02-15 10:05 UTC by q-abe

## チケットURL
Closes # (今回なし)

## 対応内容
- Footerコンポーネントの作成

## 妥協点
- 幅を一番小さくした時に文字が重なってしまう。

 ## やったこと
- gridで配置 (2箇所)
- CSSの色々な渡し方

## やってないこと
特になし。

## レビュー観点
- propsの過不足がないか
- スタイリング漏れがないか
- 変数名が適切か

2024-02-15 10:14 UTC, q-nishimura commented
![image](https://github.com/q-abe/techlab-clone/assets/30488278/4104669e-b65f-4f19-ac48-579143999b59)
本家のように、横に広げた時に伸びすぎないようにお願いします

2024-02-15 10:44 UTC, q-nishimura requested changes

2024-02-15 10:44 UTC, q-nishimura commented on src/components/molecules/Accordion.tsx
> +    cssColor: SerializedStyles;
２つともある理由がわかりづらいので、対象のエレメント（コンポーネント）の名前を入れるなどしてください

2024-02-15 10:44 UTC, q-nishimura commented on src/components/molecules/Accordion.tsx
>  type SAccordionProps = {
今回の変更ではないですが、typo?

2024-02-15 10:44 UTC, q-nishimura commented on src/components/atoms/button/TagButton.tsx
> +    isHover: boolean;
is~~~ は「〜〜であるかどうか」という使い方なのでちょっと意味合いが違います。
とはいえあんましっくりくる書き方ないんですが
hoverable
hoverAction
hover
あたりでお願いします

2024-02-15 10:44 UTC, q-nishimura commented on src/components/organisms/Footer.stories.tsx
> +export const monthlyArchive: Story = {
名前変え忘れてます

2024-02-15 10:44 UTC, q-nishimura commented on src/components/organisms/Footer.tsx
> +    const allTags = [ "HTML",
TagMockData を使ってください。

2024-02-15 10:44 UTC, q-nishimura commented on src/components/organisms/Footer.tsx
> +const section1Style = css`
本当に単に繰り返すだけでやむを得ない場合などを除いては1, 2, 3のようにはしたくないので、今回でいえばcategorySectionStyle, archiveSectionStyle, descriptionSectionStyle のようにしてください

2024-02-16 01:02 UTC, q-abe commented on src/components/molecules/Accordion.tsx
> +    cssColor: SerializedStyles;
変更しました。
[10bae9e](https://github.com/q-abe/techlab-clone/pull/23/commits/10bae9ec5730acc7e519f49cc0944814fc69902a)

2024-02-16 01:03 UTC, q-abe commented on src/components/molecules/Accordion.tsx
>  type SAccordionProps = {
SingleのSでしたが、名称変更時に変更漏れてました💦
変更いたしました。
[10bae9e](https://github.com/q-abe/techlab-clone/pull/23/commits/10bae9ec5730acc7e519f49cc0944814fc69902a)

2024-02-16 01:05 UTC, q-abe commented on src/components/atoms/button/TagButton.tsx
> +    isHover: boolean;
hoverAbleで変更しました。
今思うとhasHoverとかもありな気がしましたがどうですか？

[10bae9e](https://github.com/q-abe/techlab-clone/pull/23/commits/10bae9ec5730acc7e519f49cc0944814fc69902a)

2024-02-16 01:06 UTC, q-abe commented on src/components/organisms/Footer.stories.tsx
> +export const monthlyArchive: Story = {
変更漏れ失礼しました...
変更いたしました。
[10bae9e](https://github.com/q-abe/techlab-clone/pull/23/commits/10bae9ec5730acc7e519f49cc0944814fc69902a)

2024-02-16 01:06 UTC, q-abe commented on src/components/organisms/Footer.tsx
> +    const allTags = [ "HTML",
MockDataを使用しました。
[5d4eed0](https://github.com/q-abe/techlab-clone/pull/23/commits/5d4eed01f23d39f910a2b5bbf24e50207466fbb3)

2024-02-16 01:09 UTC, q-abe commented on src/components/organisms/Footer.tsx
> +const section1Style = css`
divStyleとかと同じ感覚で命名してました...
ナンバリングはCSSでも避けるべきなんですね。

変更いたしました。
[10bae9e](https://github.com/q-abe/techlab-clone/pull/23/commits/10bae9ec5730acc7e519f49cc0944814fc69902a)

2024-02-16 01:13 UTC, q-abe commented
画面幅的に広げられなくて、ズームアウトしても伸びないように対応いたしました。
同義で問題ないでしょうか？

<img width="1329" alt="スクリーンショット 2024-02-16 10 11 04" src="https://github.com/q-abe/techlab-clone/assets/156041244/397bc65c-a9d9-462c-a732-d7d06c6bda24">

2024-02-16 01:15 UTC, q-nishimura commented on src/components/molecules/Accordion.tsx
> +    cssColor: SerializedStyles;
👍

2024-02-16 01:41 UTC, q-abe commented on src/components/organisms/Footer.tsx
> +    const allTags = [ "HTML",
TOPページ作成に入って気づきましたが、実際のJSONデータはTOPから受け取る形にするべきでした。

2024-02-16 01:41 UTC, q-nishimura commented
@q-abe 本家の方の画像貼ってました。すみません
max-widthの指定で合ってます。
修正ありがとうございます

2024-02-16 01:41 UTC, q-nishimura approved these changes

2024-02-16 01:43 UTC, merged