symbolコンポーネント作成
q-abe/techlab-clone pull request #9
Opened 2024-02-01 06:39 UTC by q-abe

2024-02-05 12:24 UTC, q-nishimura requested changes

2024-02-05 12:24 UTC, q-nishimura commented on src/components/atoms/symbols/CloseIcon.tsx
> +import React, { FC } from "react";
CloseIconだけの問題ではないのですが代表としてここに。
アイコンの大きさがバラバラなので、基本の大きさを統一してください。

<img width="1085" alt="image" src="https://github.com/q-abe/techlab-clone/assets/30488278/55dd8d71-81cb-4488-95f4-26b428e160aa">

<img width="1330" alt="image" src="https://github.com/q-abe/techlab-clone/assets/30488278/47382091-dda1-4b05-9230-ea137923b431">

2024-02-05 12:24 UTC, q-nishimura commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
Storyのグループを作れるので、"Atoms" "Symbols" のようなグループを作成してください

2024-02-05 12:29 UTC, q-nishimura requested changes

2024-02-05 12:29 UTC, q-nishimura commented on src/components/atoms/symbols/CloseIcon.tsx
> +        <div>
これもSVGの✗があるはずです

2024-02-05 12:29 UTC, q-nishimura commented on src/components/atoms/symbols/QImgLogo.stories.tsx
> +    title: "QImgLogo",
Img のように省略するルールで作る場合もなくはないと思いますが、今回そうではないので普通にImageと書いた方がいいです。

2024-02-06 02:28 UTC, q-abe commented on src/components/atoms/symbols/QImgLogo.stories.tsx
> +    title: "QImgLogo",
省略をやめました！
[2d6d56b](https://github.com/q-abe/techlab-clone/pull/9/commits/2d6d56b5039c9b16722d81f1144d519f913330aa)

2024-02-06 02:30 UTC, q-abe commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
指定いただいた場所ではないところでできましたが、
グループの作成 ＝ フォルダ階層の認識であっていましたでしょうか。
[283f12c](https://github.com/q-abe/techlab-clone/pull/9/commits/283f12cbc2326f4a8febfec2c66d3ac5040d3c11)

2024-02-06 02:33 UTC, q-abe commented on src/components/atoms/symbols/CloseIcon.tsx
> +        <div>
作成時に探したのですが見つかりませんでした。。。
再度探しましたが、やはり見つからずです💦

なにか見つけ方があるのでしょうか？
![スクリーンショット 2024-02-06 11 32 02](https://github.com/q-abe/techlab-clone/assets/156041244/4763fd24-4b5c-444b-8da5-ac9c25b2d9e2)

2024-02-06 03:07 UTC, q-abe commented on src/components/atoms/symbols/CloseIcon.tsx
> +import React, { FC } from "react";
大きさ指定してTech Labと同じサイズにいたしました。
指定したものの親コンポーネントで再定義もできるのを確認してます。

×に関しては下記でSVGにできていないため未対応です。

[84d818a](https://github.com/q-abe/techlab-clone/pull/9/commits/84d818ab3bdac3ecff94596debdf59ad864fdf02)

2024-02-06 03:13 UTC, q-nishimura commented on src/components/atoms/symbols/CloseIcon.tsx
> +import React, { FC } from "react";
修正ありがとうございます

2024-02-06 03:15 UTC, q-nishimura commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
@q-abe 確認しました。

> グループの作成 ＝ フォルダ階層の認識であっていましたでしょうか。

特別に別枠で分けるということも有り得そうですが、今回はこれで問題ないです

2024-02-06 03:24 UTC, q-nishimura commented on src/components/atoms/symbols/CloseIcon.tsx
> +        <div>
@q-abe すいません。borderなんですね。自分が確認してませんでした。
コピー課題なのでボーダーにしときましょうか

ちなみに、SVGはタグでしかないのでこういう単純なやつなら拾ってきて使うことも可能です　↓とか
https://codepen.io/jsonUK/pen/RqgeGp

2024-02-06 03:26 UTC, q-nishimura approved these changes

2024-02-06 03:28 UTC, q-nishimura commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
@q-abe stories.tsxのファイル自体は動かさずコンポーネント本体の隣のままで合ってます。
あくまでstoryの表示上でグルーピングされていれば大丈夫です

2024-02-06 03:35 UTC, q-abe commented on src/components/atoms/symbols/CloseIcon.tsx
> +        <div>
正直、SVGのがわかりやすいのでSVGでやりたいですが、
調整に時間かかりそうなのでこのまま行きます！

例ありがとうございます！

2024-02-06 03:38 UTC, q-abe commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
まとめてしまいたかったので上記のご指摘とは別に対応してますが、
stories.tsxのファイルは動かさない方がいいでしょうか？

2024-02-06 03:38 UTC, q-abe commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
@q-nishimura 
まとめてしまいたかったので上記のご指摘とは別に対応してますが、
stories.tsxのファイルは動かさない方がいいでしょうか？

2024-02-06 03:38 UTC, q-abe commented on src/components/atoms/symbols/CloseIcon.tsx
> +        <div>
@q-nishimura 
正直、SVGのがわかりやすいのでSVGでやりたいですが、
調整に時間かかりそうなのでこのまま行きます！

例ありがとうございます！

2024-02-06 03:58 UTC, q-nishimura commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
@q-abe はい。
隣にすぐあった方が開発がしやすいです。

2024-02-06 04:13 UTC, q-abe commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
承知しました！
revertで対応しました。
(コミット分けとくと簡単に戻せていいですね💡)
[8b770ee](https://github.com/q-abe/techlab-clone/pull/9/commits/8b770eef5439700624acebe58bc4caa9bd0bedd6)

2024-02-06 04:15 UTC, q-nishimura commented on src/components/atoms/symbols/ArticleTitleText.stories.tsx
>  type Story = StoryObj<typeof meta>;
修正ありがとうございます

2024-02-06 04:21 UTC, q-nishimura approved these changes

2024-02-06 05:15 UTC, merged